# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
 - stage: 'Build Stage'
   jobs: 
    - job: 'BuildJob'
      pool:
        vmImage: 'windows-latest'

      variables:
        solution: '**/*.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'

      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'

 - stage: 'Deploy To Dev'
   dependsOn: 'Build Stage'
   jobs:
     - job: 
       pool: 
        vmImage: 'windows-latest'
       steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Pipeline.Workspace)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure for Students (9dccc2fd-f54b-41f4-93af-075a94f30522)'
            appType: 'webApp'
            WebAppName: 'demo-webapp-yaml'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        
 - stage: 'Deploy To QA'
   dependsOn: 'Deploy To Dev'
   jobs:
     - job: 
       pool: 
        vmImage: 'windows-latest'
       steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Pipeline.Workspace)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure for Students (9dccc2fd-f54b-41f4-93af-075a94f30522)'
            appType: 'webApp'
            WebAppName: 'qa-for-yaml'
            deployToSlotOrASE: true
            ResourceGroupName: 'ayush_rg'
            SlotName: 'staging'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        - task: AzureAppServiceManage@0
          inputs:
            azureSubscription: 'Azure for Students (9dccc2fd-f54b-41f4-93af-075a94f30522)'
            Action: 'Swap Slots'
            WebAppName: 'qa-for-yaml'
            ResourceGroupName: 'ayush_rg'
            SourceSlot: 'staging'